name: Release to GHCR

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/tobias954/assignment3_maio:${{ github.ref_name }}

  smoke_test:
    runs-on: ubuntu-latest
    needs: build_and_push
    continue-on-error: true   # push blockeras inte om smoketest faller
    steps:
      - name: Pull + run
        run: |
          docker pull ghcr.io/tobias954/assignment3_maio:${{ github.ref_name }}
          docker run -d -p 8080:8080 -e MODEL_VERSION=v0.2 ghcr.io/tobias954/assignment3_maio:${{ github.ref_name }}
          sleep 5
          curl -f http://localhost:8080/health
