name: Release to GHCR

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/tobias954/assignment3_maio

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (PAT)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tobias954
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ github.ref_name }}

  smoke-test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Pull & run
        run: |
          docker pull ${{ env.IMAGE }}:${{ github.ref_name }}
          docker run -d -p 8080:8080 -e MODEL_VERSION=v0.2 ${{ env.IMAGE }}:${{ github.ref_name }}
          sleep 8
          curl -f http://localhost:8080/health
